name: 02 - Docker Build

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: devsecops-demo:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max